#pragma once

#define PAPERMONO_FW_VERSION "0.1.9-beta"
/* Status poll. Do not go much faster: SSD1677 must not stream partial refreshes. */
#define PAPERMONO_POLL_MS 15000
#define PAPERMONO_PAGE_HOME 0
#define PAPERMONO_PAGE_STATUS 1
#define PAPERMONO_PAGE_HEALTH 2
#define PAPERMONO_PAGE_PLANS 3
#define PAPERMONO_PAGE_NOTE 4
#define PAPERMONO_PAGE_BOARD 5
#define PAPERMONO_PAGE_LYMOW 6
#define PAPERMONO_PAGE_RADIO 7
#define PAPERMONO_PAGE_DEVICE 8
#define PAPERMONO_PAGE_COUNT 9
#define PAPERMONO_PLAN_MAX 20
#define PAPERMONO_PLAN_VISIBLE 6
#define PAPERMONO_PEER_MAX 8
#define PAPERMONO_INBOX_MAX 8
#define PAPERMONO_MSG_CHARS 180
