#pragma once

#define PAPERMONO_FW_VERSION "0.2.9-colour"
#define PAPERMONO_POLL_MS 60000
#define PAPERMONO_PAGE_HOME 0
#define PAPERMONO_PAGE_STATUS 1
#define PAPERMONO_PAGE_HEALTH 2
#define PAPERMONO_PAGE_PLANS 3
#define PAPERMONO_PAGE_POWERWALL 4
#define PAPERMONO_PAGE_LYMOW 5
#define PAPERMONO_PAGE_BOARD 6
#define PAPERMONO_PAGE_COUNT 7
#define PAPERMONO_PLAN_MAX 20
#define PAPERMONO_PLAN_VISIBLE 6
