CREATE TABLE IF NOT EXISTS installs (
  id TEXT PRIMARY KEY,
  version TEXT NOT NULL DEFAULT '',
  yarbo INTEGER NOT NULL DEFAULT 0,
  powerwall INTEGER NOT NULL DEFAULT 0,
  lymow INTEGER NOT NULL DEFAULT 0,
  vestaboard INTEGER NOT NULL DEFAULT 0,
  papermono INTEGER NOT NULL DEFAULT 0,
  papercolor INTEGER NOT NULL DEFAULT 0,
  os TEXT NOT NULL DEFAULT '',
  first_seen INTEGER NOT NULL,
  last_seen INTEGER NOT NULL
);
