name = "yarbo-panel-metrics"
main = "src/worker.js"
compatibility_date = "2026-09-25"
workers_dev = true
preview_urls = false

[[d1_databases]]
binding = "DB"
database_name = "yarbo-panel-metrics"
database_id = "86439e37-32fd-4349-8fac-862379efe8b7"
